[ISSUE #1] grpc 集成polaris服务注册发现
polarismesh/grpc-java-polaris pull request #3
Opened 2021-12-05 14:23 UTC by li-xiao-shuang

fix : #1

2021-12-05 15:17 UTC, chuntaojun commented on grpc-java-polaris/src/main/java/com/tencent/polaris/grpc/server/ServerAgent.java
> +            log.error("abnormal port");
那这里应该提前终止？

2021-12-05 15:17 UTC, chuntaojun commented on grpc-java-polaris/src/main/java/com/tencent/polaris/grpc/server/ServerAgent.java
> +        }, 0, 500, TimeUnit.MILLISECONDS);
500ms 一次心跳？？？

2021-12-05 15:17 UTC, chuntaojun commented on grpc-java-polaris/src/main/java/com/tencent/polaris/grpc/server/ServerAgent.java
> +public class ServerAgent {
这个名字是不是改一改比较好

2021-12-05 15:17 UTC, chuntaojun commented on grpc-java-polaris/src/main/java/com/tencent/polaris/grpc/server/ServerAgent.java
> +        request.setNamespace("default");
这里的命名空间不应该写死，应该是可以从某一个地方读取到的才对

2021-12-07 08:19 UTC, chuntaojun requested changes

2021-12-07 08:19 UTC, chuntaojun commented on grpc-java-polaris/src/main/java/com/tencent/polaris/grpc/resolver/PolarisNameResolver.java
> +        log.info("getAllInstance response:{}", response);
这个debug级别就好了

2021-12-07 08:19 UTC, chuntaojun commented on grpc-java-polaris/src/main/java/com/tencent/polaris/grpc/resolver/PolarisNameResolver.java
> +        consumerAPI.destroy();
这个还是存在

2021-12-07 08:19 UTC, chuntaojun commented
相关注释都使用英文注释吧

2021-12-07 09:29 UTC, chuntaojun commented on grpc-java-polaris/src/main/java/com/tencent/polaris/grpc/resolver/PolarisNameResolverProvider.java
> +    public PolarisNameResolverProvider(String namespace, String service) {
这里NameResolverProvider应该不能设置Namespace以及Service，有可能涉及跨namespace以及多service调用，那这里就无法满足了

2021-12-07 09:29 UTC, chuntaojun commented on grpc-java-polaris/src/main/java/com/tencent/polaris/grpc/resolver/PolarisNameResolverProvider.java
> +        return new PolarisNameResolver(namespace, service);
应该是从URL去解析对应的服务以及命名空间然后去获取一个provider实例

2021-12-07 12:34 UTC, chuntaojun commented on grpc-java-polaris/src/main/java/com/tencent/polaris/grpc/server/PolarisGrpcServer.java
> +    private final int ttl = 2;
TTL默认5秒吧

2021-12-07 12:34 UTC, chuntaojun commented on grpc-java-polaris/src/main/java/com/tencent/polaris/grpc/server/PolarisGrpcServer.java
> +        log.info("Virtual machine shut down Anti-registration service");
Anti-registration => deregister

2021-12-07 12:34 UTC, chuntaojun commented on grpc-java-polaris/src/main/java/com/tencent/polaris/grpc/server/PolarisGrpcServer.java
> +        request.setTtl(ttl);
这里最好能够提供给用户可以设置metadata的入口，否则用户想设置metadata都找不到地方去操作

2021-12-07 13:35 UTC, li-xiao-shuang commented on grpc-java-polaris/src/main/java/com/tencent/polaris/grpc/server/PolarisGrpcServer.java
> +    private final int ttl = 2;
> 

服务端使用这个时间干什么了嘛？

2021-12-07 13:36 UTC, li-xiao-shuang commented on grpc-java-polaris/src/main/java/com/tencent/polaris/grpc/server/PolarisGrpcServer.java
> +    private final int ttl = 2;
> 

2秒是频率太高了？

2021-12-08 07:21 UTC, chuntaojun commented on grpc-java-polaris/src/main/java/com/tencent/polaris/grpc/resolver/PolarisNameResolverProvider.java
> +    public static void main(String[] args) {
这里转移到单元测试里面

2021-12-08 07:21 UTC, chuntaojun commented on grpc-java-polaris/src/main/java/com/tencent/polaris/grpc/server/PolarisGrpcServer.java
> +        providerAPI.destroy();
方法只做一个事情，这里就不要 providerAPI.destroy();

2021-12-10 13:54 UTC, chuntaojun approved these changes

2021-12-10 15:28 UTC, andrewshan commented on grpc-java-polaris-example/src/main/java/com/tencent/polaris/grpc/server/ServerMain.java
> +                .namespace("default")
namespace是否可选？假如不填namespace，默认default？

2021-12-10 15:33 UTC, andrewshan commented on grpc-java-polaris/src/main/java/com/tencent/polaris/grpc/server/PolarisGrpcServer.java
> +    private final int ttl = 5;
ttl也应该可以被设置

2021-12-10 15:33 UTC, andrewshan commented on grpc-java-polaris/src/main/java/com/tencent/polaris/grpc/server/PolarisGrpcServer.java
> +    private final ScheduledExecutorService executorService = new ScheduledThreadPoolExecutor(5);
这里最好搞成单线程的线程池用于心跳上报

2021-12-10 15:33 UTC, andrewshan commented on grpc-java-polaris/src/main/java/com/tencent/polaris/grpc/server/PolarisGrpcServer.java
> +    private final ScheduledExecutorService executorService = new ScheduledThreadPoolExecutor(5);
线程池要进行命名，方便问题定位

2021-12-10 15:33 UTC, andrewshan commented on grpc-java-polaris/src/main/java/com/tencent/polaris/grpc/util/IpUtil.java
> +    public static String getLocalHost() {
最好直接通过与server端直接的tcp connect来获取源IP信息

2021-12-12 07:29 UTC, merged